### Register User
POST http://localhost:8082/api/v1/auth/register
Content-Type: application/json

{
  "nomEt": "Ali",
  "prenomEt": "Bouali",
  "email": "alibou1@gmail.com",
  "password": "password",
  "cin": 8954665,
  "ecole": "esprit",
  "dateNaissance":"2023-02-02",
  "role":  "ADMIN"
}

> {% client.global.set("auth-token", response.body.access_token);  %}

### Query the Demo endpoint
GET http://localhost:8082/api/v1/etu/57
Authorization: Bearer {{auth-token}}

### Change the password
PATCH http://localhost:8082/api/v1/users
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "currentPassword": "password",
  "newPassword": "newPassword",
  "confirmationPassword":  "newPassword"
}

### Login again and update the token
POST http://localhost:8082/api/v1/auth/authenticate
Content-Type: application/json

{
  "email":  "alibou1@gmail.com",
  "password": "newPassword"
}

> {% client.global.set("new-auth-token", response.body.access_token);  %}


### Query the Demo endpoint after password change
GET http://localhost:8082/api/v1/etu/57
Authorization: Bearer {{new-auth-token}}